version: '3.8'

services:
  meilisearch:
    image: getmeili/meilisearch:v1.12
    container_name: lego_meilisearch
    environment:
      - MEILI_ENV=development
      - MEILI_MASTER_KEY=Lego_CAD_Sim_Meili_Master_Key_2026
    ports:
      - "7700:7700"
    volumes:
      - ./data/meili_data:/meili_data
    restart: always

volumes:
  meili_data:
